### ISSUE TITLE
Mine Limit Bug

### ISSUE THREAD

**Issue by kajendra** [Factorio-Biter-Battles/Factorio-Biter-Battles#146]
The mines PR #140 has a few issues, it killed the server after the limit was reached and then a new round started.
@derkachdaniil 

We tested this by creating 3000 mines. After placing 3000 mines, the limit was correctly reached.
It worked elegantly and would even print how many mines were left, which was beautiful! :)

Bug 1: We noticed that placing additional mines past the limit would still increase the MVP Builder points.

When the mines were destroyed, new mines could be placed and the limit would be reached again and worked successfully.

The issue began when a new round was created.
Bug 2: When a new round was created and mines were placed, it caused server desyncs.

This occurred only after the limit was reached and a new round was started.

**Comment by Hornwitser** [comment]
Major issue: count is not stored in the `global` table, so each player ends up with the limit set to 0 when they join, desyncing the game when mines are place.

**Comment by 1pulse** [comment]
> Major issue: count is not stored in the `global` table, so each player ends up with the limit set to 0 when they join, desyncing the game when mines are place.

u last PR was resolving this, not?

**Comment by Hornwitser** [comment]
If by resolving it you mean removing it entirely, then yes the issues here are no more.

**Comment by Ragnarok77-factorio** [comment]
There is no mine anymore, closed
