### ISSUE TITLE
Spectators can send fish

### ISSUE THREAD

**Issue by cogito123** [Factorio-Biter-Battles/Factorio-Biter-Battles#173]
If a spectator opens a tech tree, he will be swapped to that team. Once he leaves it, team menu will be available for few seconds and it can be used to send spy fish or click "Join spectator" again and keep rejoining as spectator.

**Comment by Ragnarok77-factorio** [comment]
Tested it, you can't see tech of team anymore in spect, should be fixed then..? I don't send spy button when I switch from north/south to spectator too
