### ISSUE TITLE
Ores near starting area are getting truncated

### ISSUE THREAD

**Issue by cogito123** [Factorio-Biter-Battles/Factorio-Biter-Battles#177]
The `terrain.lua::clear_ore_in_main` function is truncating some of the ores around starting area. The root cause is that this function doesn't take whole ore vein into consideration, but destroys resource tiles based strictly on search area.
![Screenshot_from_2021-06-10_01-02-20](https://user-images.githubusercontent.com/59515242/121554128-2a219c80-ca12-11eb-898c-c3070c870db7.png)

**Comment by Ragnarok77-factorio** [comment]
was closed long time ago with PR#178, unsure why it didn't auto close the issue
