### ISSUE TITLE
Player auto tagging

### ISSUE THREAD

**Issue by cogito123** [Factorio-Biter-Battles/Factorio-Biter-Battles#179]
Add mechanism to auto tag people by their x axis position and by looking at clusters of players. If cluster is far from main base assign them for example a tag "East" or "West". This will make chat less confusing between outposters and main base.

Requested by: z-em.

**Comment by Ragnarok77-factorio** [comment]
Done by https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/pull/239
