### ISSUE TITLE
Difficulty modifier for number of players

### ISSUE THREAD

**Issue by DashCee** [Factorio-Biter-Battles/Factorio-Biter-Battles#27]
I think the best way to deal with the real difficulty of a game is to add a modifier to, in real time, scale the difficulty of the game according to the number of players on each team, on top of the chosen difficulty modifier, which is more of a game speed modifier than anything tbh.

That would also stop people from heavily stacking one side, as there would be no benefit of doing so.

I've seen nightmare game is lasting longer than previous 'Piece of Cake' difficulty games, due to the low number of players online at the time. (4 per team, neither very good, 58mins compared to 1h 45m nightmare game followed by 50m nightmare game. Difficulty isn't reflected when player count matters far more.)

**Comment by kajendra** [comment]
Suggesting to close this.
The game already has difficulty mod for Threat based on player count here:
https://github.com/Factorio-Biter-Battles/Factorio-Biter-Battles/blob/f8fe3a3eff97d07b1c5ce28355acde7314fd8121/maps/biter_battles_v2/feeding.lua#L15

We could implement something similar for evo, but I don't think it's necessary given the current game state.
