### ISSUE TITLE
Persistent data store

### ISSUE THREAD

**Issue by DashCee** [Factorio-Biter-Battles/Factorio-Biter-Battles#28]
Lightweight or serverless persistent database or server hosted basic datastore file creation for the purpose of containing player stats. MongoDB, AWS RDS, Redis etc would work if anyone has experience with cloud hosting, or a simple CSV file hosted on the factorio server would do too if anyone has the knowhow to read/write in lua.

If we start storing player stats like total biter kills,  wins, losses, win/loss ratio, etc we could then easily implement levels and whatnot, which would be great at allowing experienced players to herd newbros when they join. This could also be the thing used to select who is qualified to add to the research queue, instead of the current suggestion of trusted players only, if trusted players are online.

**Comment by 1pulse** [comment]
important feature I planed to work on, but will need help, anyone have some skills and time ?

**Comment by 1pulse** [comment]
did it with mysql without lua
