### ISSUE TITLE
Research queue update verification

### ISSUE THREAD

**Issue by DashCee** [Factorio-Biter-Battles/Factorio-Biter-Battles#29]
Set the research queue to only allow admins and trusted users to update the research queue. If neither an admin nor a trusted member are present within a team, research queue access is granted to everyone.

This will stop stubborn noobs from persistently adding red belts, trains, circuit network, gates etc to the research queue.

**Comment by 1pulse** [comment]
hum, or just permit to the 1/3 most experienced ppl on the team (by time on the map) to do this action?

**Comment by Ragnarok77-factorio** [comment]
There was a vote about it, rejected : 
https://discord.com/channels/823696400797138974/823771211421974579/925042801299820564
