### ISSUE TITLE
Multiplayer server name standardisation

### ISSUE THREAD

**Issue by DashCee** [Factorio-Biter-Battles/Factorio-Biter-Battles#30]
Whenever one server crashes and the other gets populated there is so much chaos since some people think it's the same server and others thing they've joined a completely different server due to the names of both of them. 

Standardise the naming scheme of the servers, both of them reading "factorio-biter-battle" or something similar, and if felt necessary adding the server owner (raven/redmew) to the END of the server name. Add the red text to the name of the gametype, not the owner too. 

Even I didn't realise they were both running the same codebase for the first few days until someone told me, since there was no real indication until redmew added "raven's biter battles" to the end of the server name in a plain colour that everyone skips over for the bright red "MewMew"

**Comment by 1pulse** [comment]
not sure to understand, how would be new main server name so? and backup / other ones?

**Comment by kajendra** [comment]
I think they meant
Biter Battle - Raven Version

But I think what we have is clear now and follows convention of Comfy and RedMew :)
Closing :)
