### ISSUE TITLE
Spectators/Disconnects Drop Inventory

### ISSUE THREAD

**Issue by DashCee** [Factorio-Biter-Battles/Factorio-Biter-Battles#31]
Players who leave should drop their inventory. I've seen players actively removing expensive constructs like electric miners early on and spectate/leave the game to spite teammates, as well as newbies leaving with what is usually an inventory that has too many items in it. 

Would be nice to drop a chest or a corpse to be looted upon switching to spectator mode or upon disconnect.

**Comment by guymaor86** [comment]
if someone does it out of spite then we should ban people like that

dont know if i completely agree about this feature, if i need to go AFK for 10 min and i spectate i dont want my stuff to go away

**Comment by 1pulse** [comment]
very hard to manage this, even if it's important in some situations. Maybe we should  show a "code of conduct / basic rules" on each load of the map for all players < 10h on the map for ensure noobs read it and do less waste

**Comment by Ragnarok77-factorio** [comment]
Need vote on discord for new feature.
