### ISSUE TITLE
Ignore doesnt work

### ISSUE THREAD

**Issue by Ragnarok77-factorio** [Factorio-Biter-Battles/Factorio-Biter-Battles#316]
When you ignore someone (/ignore playerName), you can still see his text message. Probably caused by share chat, unsure if there is a way to know who ignored who..

**Comment by TheBigZet** [comment]
We could probably listen to /ignore when it's called (on_console_command(), and do some processing then

**Comment by Ragnarok77-factorio** [comment]
Bumping it, would be nice to get it fixed, it would reduce drama as people could fully ignore someone.
