### ISSUE TITLE
Server name version

### ISSUE THREAD

**Issue by DashCee** [Factorio-Biter-Battles/Factorio-Biter-Battles#33]
Simply add ***UPDATED*** or something to the server browser title, as comfy has v3 in their name where we have nothing, so people might think we're running very old versions. Better yet,  the last release date.

**Comment by 1pulse** [comment]
yes, admins can change server name with date of last release

**Comment by 1pulse** [comment]
also, I can do it when I upload new map, if nobody oppose I'll add release date

**Comment by 1pulse** [comment]
@sanctorio know how to change server name ingame

**Comment by 1pulse** [comment]
too old
