### ISSUE TITLE
Biters not targeting silo

### ISSUE THREAD

**Issue by DashCee** [Factorio-Biter-Battles/Factorio-Biter-Battles#45]
Biters often completely avoid the silo once they have made it into a base, even going as far as to circle the silo but attacking everything that isn't the silo. I think the target priority (silo) is lost when the biters start engaging anything nearby until they completely run out of things nearby to destroy.
Biter AI is also very inconsistent, sometimes targeting outposts, sometimes not, with no real way to tell if an outpost will be targeted or not, leading to frustration when outposting.

**Comment by 1pulse** [comment]
Hum, It's true silo is not so targeted but if u need more fast target, why don't u add / edit code-source and send a PR?
