### ISSUE TITLE
Allow other participants to tag issues

### ISSUE THREAD

**Issue by DashCee** [Factorio-Biter-Battles/Factorio-Biter-Battles#46]
Nice to see issues being updated, commented and tagged recently, but it seems that only those with heightened perms are able to tag an issue. Would be nice, if possible, to allow the creator of an issue to tag their own story.

**Comment by 1pulse** [comment]
can u explain me how to do that? Yes would be nice for admins too :)

**Comment by guymaor86** [comment]
you need to change the permissions of users on this repo, this might help:
https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#permission-levels-for-repositories-owned-by-an-organization
