### ISSUE TITLE
Biter Path Space Issues

### ISSUE THREAD

**Issue by kajendra** [Factorio-Biter-Battles/Factorio-Biter-Battles#53]
From observing biter path planning through the debug settings, we can see that only in the late game (4+ hours) the biter paths are overly extensive.

For example, the North biters will try to path to the silo through most of the North map area, but it will include the uncovered regions of the map. This part isn't incorrect so far.

The biters will then attempt to path through the uncovered region and include the other side on their search space.

Crude example:
![image](https://user-images.githubusercontent.com/9014676/102690432-5e3ea200-41d3-11eb-858b-4f4c7fde6206.png)

This tends to happens only late in the game, and when there are several walls. And when the uncovered map isn't as wide as tall.
Limiting the search space to only the biter's originating side would be wise.

I don't think limiting the search space to only visible tiles is practical.

If I see a map like this again, I will try to include a picture of it.

**Comment by 1pulse** [comment]
each big game with 100% reach on server, once silo explode, all is fine again and cpu reach 'normal' utilization again... so yes, definitively have anything bad impacting all the time the cpu... not only during attacks or even crazy path finding trying to go to enemy team

**Comment by kajendra** [comment]
Here is an image showing the pathing computation for reference:

![image](https://user-images.githubusercontent.com/9014676/103182369-d6166780-4878-11eb-93eb-824659d0d770.png)

**Comment by kajendra** [comment]
I looked at a map today and saw it wasn't lagging when more of the river was revealed. These issues only occur when the river is not visible so the biters try to path across it.

I think a dirty solution to this is to reveal the river when the map's edge doesn't have the river uncovered and is lagging.

Admins could use the command:
/c local radius=100 game.player.force.chart(game.player.surface, {{-radius, -1}, {radius, 1}})

**Comment by guppyfaced** [comment]
Update:

Although increasing the revealed chunks helps occasionally, the error still occurs, even with the radius at 4000 units wide. See attached.

![node hell](https://user-images.githubusercontent.com/32272137/105040436-22149080-5a62-11eb-9f92-a8c0380c63fc.jpeg)

![nodes crossing](https://user-images.githubusercontent.com/32272137/105040447-250f8100-5a62-11eb-9e91-0e76ae9a7959.jpeg)
