### ISSUE TITLE
Prevent sending science until the difficulty level voting ends

### ISSUE THREAD

**Issue by mysticamber** [Factorio-Biter-Battles/Factorio-Biter-Battles#63]
Prevent sending science until the difficulty level voting ends

**Comment by guymaor86** [comment]
dont see it as an urgent issue. if voting is 5 minutes. how much science can you actually send in that time?

**Comment by guppyfaced** [comment]
When the difficulty vote is reopened mid-game, some cunning players send 500 purple flasks when the mode changes to normal or above.

**Comment by AwesomePatrol** [comment]
Fixed (at least partially) in https://github.com/AwesomePatrol/ComfyFactorio/commit/cfc01a2b37b42a8a09fc5206ca22ef11a8a9e28f
It will be pulled with other Raven's changes to difficulty scaling after testing.

**Comment by kajendra** [comment]
It seems #108 is the original source of the fix. Somehow code in #128 was merged first?
It does solve #63 I think?

**Comment by AwesomePatrol** [comment]
Already on `master`.
