### ISSUE TITLE
Add How to Test to Readme

### ISSUE THREAD

**Issue by kajendra** [Factorio-Biter-Battles/Factorio-Biter-Battles#65]
Add guidelines on how to test modified code for Contributors.

Also potentially move this to the Wiki and add a link to the Wiki to clear the main page of some Clutter.
Thoughts?

**Comment by guymaor86** [comment]
i agree, the readme.md is very messy and could use some love

**Comment by Ragnarok77-factorio** [comment]
Was closed by PR 106 which was merged
